{% set name = "dask-snowflake" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 750aedbdee120c70c3d1ced1bf6f8d953b929f9173f2abb26ae99491310a3e0c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - dask
    - distributed
    - pandas
    - pyarrow
    - snowflake-connector-python >=2.6.0
    - snowflake-sqlalchemy

test:
  imports:
    - dask_snowflake
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/coiled/dask-snowflake
  license: BSD-3-Clause
  license_family: MIT
  license_file: LICENSE
  summary: Dask integration for Snowflake
  description: |
    Dask integration for Snowflake
  doc_url: https://github.com/coiled/dask-snowflake
  dev_url: https://github.com/coiled/dask-snowflake

extra:
  recipe-maintainers:
    - jrbourbeau
    - fjetter
