{% set name = "dask-snowflake" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5cb58b99981ef35bd32510bf54ada3132689b56f76e16d54b774834b3bf95391

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - dask >=2024.3.0
    - pandas <2.2
    - pyarrow
    - snowflake-connector-python >=2.6.0
    - snowflake-sqlalchemy
    - sqlalchemy

test:
  imports:
    - dask_snowflake
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/coiled/dask-snowflake
  license: BSD-3-Clause
  license_family: MIT
  license_file: LICENSE
  summary: Dask integration for Snowflake
  description: |
    Dask integration for Snowflake
  doc_url: https://github.com/coiled/dask-snowflake
  dev_url: https://github.com/coiled/dask-snowflake

extra:
  recipe-maintainers:
    - jrbourbeau
    - fjetter
