{% set name = "dask-snowflake" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9893e3bec36e0109374631f5875fe08b3bc8ffcc1fa60472149b44bdb968f577

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - dask >=2021.05.0
    - pandas
    - pyarrow
    - snowflake-connector-python >=2.6.0
    - snowflake-sqlalchemy

test:
  imports:
    - dask_snowflake
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/coiled/dask-snowflake
  license: BSD-3-Clause
  license_family: MIT
  license_file: LICENSE
  summary: Dask integration for Snowflake
  description: |
    Dask integration for Snowflake
  doc_url: https://github.com/coiled/dask-snowflake
  dev_url: https://github.com/coiled/dask-snowflake

extra:
  recipe-maintainers:
    - jrbourbeau
    - fjetter
